// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UFCfights.Data;

#nullable disable

namespace UFCfights.Migrations
{
    [DbContext(typeof(FightsContext))]
    [Migration("20260513172414_AddMatchIndex")]
    partial class AddMatchIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UFCfights.Models.Fight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("B_Height_cms")
                        .HasColumnType("float");

                    b.Property<double?>("B_Reach_cms")
                        .HasColumnType("float");

                    b.Property<string>("B_Stance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("B_Weight_lbs")
                        .HasColumnType("float");

                    b.Property<double?>("B_age")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_BODY_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_BODY_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_CLINCH_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_CLINCH_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_CTRL_time_seconds")
                        .HasColumnType("float")
                        .HasColumnName("B_avg_CTRL_time(seconds)");

                    b.Property<double?>("B_avg_DISTANCE_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_DISTANCE_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_GROUND_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_GROUND_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_HEAD_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_HEAD_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_KD")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_LEG_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_LEG_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_REV")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_SIG_STR_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_SIG_STR_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_SIG_STR_pct")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_SUB_ATT")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_TD_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_TD_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_TD_pct")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_TOTAL_STR_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_TOTAL_STR_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_BODY_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_BODY_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_CLINCH_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_CLINCH_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_CTRL_time_seconds")
                        .HasColumnType("float")
                        .HasColumnName("B_avg_opp_CTRL_time(seconds)");

                    b.Property<double?>("B_avg_opp_DISTANCE_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_DISTANCE_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_GROUND_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_GROUND_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_HEAD_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_HEAD_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_KD")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_LEG_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_LEG_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_REV")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_SIG_STR_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_SIG_STR_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_SIG_STR_pct")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_SUB_ATT")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_TD_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_TD_landed")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_TD_pct")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_TOTAL_STR_att")
                        .HasColumnType("float");

                    b.Property<double?>("B_avg_opp_TOTAL_STR_landed")
                        .HasColumnType("float");

                    b.Property<int?>("B_current_lose_streak")
                        .HasColumnType("int");

                    b.Property<int?>("B_current_win_streak")
                        .HasColumnType("int");

                    b.Property<int?>("B_draw")
                        .HasColumnType("int");

                    b.Property<string>("B_fighter")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("B_longest_win_streak")
                        .HasColumnType("int");

                    b.Property<int?>("B_losses")
                        .HasColumnType("int");

                    b.Property<int?>("B_total_rounds_fought")
                        .HasColumnType("int");

                    b.Property<double?>("B_total_time_fought_seconds")
                        .HasColumnType("float")
                        .HasColumnName("B_total_time_fought(seconds)");

                    b.Property<int?>("B_total_title_bouts")
                        .HasColumnType("int");

                    b.Property<double?>("B_win_by_Decision_Majority")
                        .HasColumnType("float");

                    b.Property<double?>("B_win_by_Decision_Split")
                        .HasColumnType("float");

                    b.Property<double?>("B_win_by_Decision_Unanimous")
                        .HasColumnType("float");

                    b.Property<double?>("B_win_by_KO_TKO")
                        .HasColumnType("float")
                        .HasColumnName("B_win_by_KO/TKO");

                    b.Property<double?>("B_win_by_Submission")
                        .HasColumnType("float");

                    b.Property<double?>("B_win_by_TKO_Doctor_Stoppage")
                        .HasColumnType("float");

                    b.Property<int?>("B_wins")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("R_Height_cms")
                        .HasColumnType("float");

                    b.Property<double?>("R_Reach_cms")
                        .HasColumnType("float");

                    b.Property<string>("R_Stance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("R_Weight_lbs")
                        .HasColumnType("float");

                    b.Property<double?>("R_age")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_BODY_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_BODY_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_CLINCH_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_CLINCH_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_CTRL_time_seconds")
                        .HasColumnType("float")
                        .HasColumnName("R_avg_CTRL_time(seconds)");

                    b.Property<double?>("R_avg_DISTANCE_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_DISTANCE_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_GROUND_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_GROUND_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_HEAD_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_HEAD_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_KD")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_LEG_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_LEG_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_REV")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_SIG_STR_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_SIG_STR_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_SIG_STR_pct")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_SUB_ATT")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_TD_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_TD_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_TD_pct")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_TOTAL_STR_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_TOTAL_STR_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_BODY_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_BODY_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_CLINCH_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_CLINCH_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_CTRL_time_seconds")
                        .HasColumnType("float")
                        .HasColumnName("R_avg_opp_CTRL_time(seconds)");

                    b.Property<double?>("R_avg_opp_DISTANCE_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_DISTANCE_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_GROUND_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_GROUND_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_HEAD_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_HEAD_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_KD")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_LEG_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_LEG_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_REV")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_SIG_STR_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_SIG_STR_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_SIG_STR_pct")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_SUB_ATT")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_TD_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_TD_landed")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_TD_pct")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_TOTAL_STR_att")
                        .HasColumnType("float");

                    b.Property<double?>("R_avg_opp_TOTAL_STR_landed")
                        .HasColumnType("float");

                    b.Property<int?>("R_current_lose_streak")
                        .HasColumnType("int");

                    b.Property<int?>("R_current_win_streak")
                        .HasColumnType("int");

                    b.Property<int?>("R_draw")
                        .HasColumnType("int");

                    b.Property<string>("R_fighter")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("R_longest_win_streak")
                        .HasColumnType("int");

                    b.Property<int?>("R_losses")
                        .HasColumnType("int");

                    b.Property<int?>("R_total_rounds_fought")
                        .HasColumnType("int");

                    b.Property<double?>("R_total_time_fought_seconds")
                        .HasColumnType("float")
                        .HasColumnName("R_total_time_fought(seconds)");

                    b.Property<int?>("R_total_title_bouts")
                        .HasColumnType("int");

                    b.Property<double?>("R_win_by_Decision_Majority")
                        .HasColumnType("float");

                    b.Property<double?>("R_win_by_Decision_Split")
                        .HasColumnType("float");

                    b.Property<double?>("R_win_by_Decision_Unanimous")
                        .HasColumnType("float");

                    b.Property<double?>("R_win_by_KO_TKO")
                        .HasColumnType("float")
                        .HasColumnName("R_win_by_KO/TKO");

                    b.Property<double?>("R_win_by_Submission")
                        .HasColumnType("float");

                    b.Property<double?>("R_win_by_TKO_Doctor_Stoppage")
                        .HasColumnType("float");

                    b.Property<int?>("R_wins")
                        .HasColumnType("int");

                    b.Property<string>("Referee")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TitleBout")
                        .HasColumnType("bit");

                    b.Property<string>("WeightClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Winner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("R_fighter", "B_fighter");

                    b.ToTable("Fights");
                });
#pragma warning restore 612, 618
        }
    }
}
