using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UFCfights.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Fights",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    R_fighter = table.Column<string>(type: "TEXT", nullable: true),
                    B_fighter = table.Column<string>(type: "TEXT", nullable: true),
                    Referee = table.Column<string>(type: "TEXT", nullable: true),
                    date = table.Column<string>(type: "TEXT", nullable: true),
                    location = table.Column<string>(type: "TEXT", nullable: true),
                    Winner = table.Column<string>(type: "TEXT", nullable: true),
                    title_bout = table.Column<bool>(type: "INTEGER", nullable: true),
                    weight_class = table.Column<string>(type: "TEXT", nullable: true),
                    B_avg_KD = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_KD = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_SIG_STR_pct = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_SIG_STR_pct = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_TD_pct = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_TD_pct = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_SUB_ATT = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_SUB_ATT = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_REV = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_REV = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_SIG_STR_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_SIG_STR_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_SIG_STR_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_SIG_STR_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_TOTAL_STR_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_TOTAL_STR_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_TOTAL_STR_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_TOTAL_STR_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_TD_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_TD_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_TD_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_TD_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_HEAD_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_HEAD_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_HEAD_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_HEAD_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_BODY_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_BODY_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_BODY_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_BODY_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_LEG_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_LEG_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_LEG_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_LEG_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_DISTANCE_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_DISTANCE_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_DISTANCE_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_DISTANCE_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_CLINCH_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_CLINCH_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_CLINCH_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_CLINCH_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_GROUND_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_GROUND_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_GROUND_att = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_opp_GROUND_landed = table.Column<double>(type: "REAL", nullable: true),
                    B_avg_CTRL_timeseconds = table.Column<double>(name: "B_avg_CTRL_time(seconds)", type: "REAL", nullable: true),
                    B_avg_opp_CTRL_timeseconds = table.Column<double>(name: "B_avg_opp_CTRL_time(seconds)", type: "REAL", nullable: true),
                    B_total_time_foughtseconds = table.Column<double>(name: "B_total_time_fought(seconds)", type: "REAL", nullable: true),
                    B_total_rounds_fought = table.Column<int>(type: "INTEGER", nullable: true),
                    B_total_title_bouts = table.Column<int>(type: "INTEGER", nullable: true),
                    B_current_win_streak = table.Column<int>(type: "INTEGER", nullable: true),
                    B_current_lose_streak = table.Column<int>(type: "INTEGER", nullable: true),
                    B_longest_win_streak = table.Column<int>(type: "INTEGER", nullable: true),
                    B_wins = table.Column<int>(type: "INTEGER", nullable: true),
                    B_losses = table.Column<int>(type: "INTEGER", nullable: true),
                    B_draw = table.Column<int>(type: "INTEGER", nullable: true),
                    B_win_by_Decision_Majority = table.Column<double>(type: "REAL", nullable: true),
                    B_win_by_Decision_Split = table.Column<double>(type: "REAL", nullable: true),
                    B_win_by_Decision_Unanimous = table.Column<double>(type: "REAL", nullable: true),
                    B_win_by_KOTKO = table.Column<double>(name: "B_win_by_KO/TKO", type: "REAL", nullable: true),
                    B_win_by_Submission = table.Column<double>(type: "REAL", nullable: true),
                    B_win_by_TKO_Doctor_Stoppage = table.Column<double>(type: "REAL", nullable: true),
                    B_Stance = table.Column<string>(type: "TEXT", nullable: true),
                    B_Height_cms = table.Column<double>(type: "REAL", nullable: true),
                    B_Reach_cms = table.Column<double>(type: "REAL", nullable: true),
                    B_Weight_lbs = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_KD = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_KD = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_SIG_STR_pct = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_SIG_STR_pct = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_TD_pct = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_TD_pct = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_SUB_ATT = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_SUB_ATT = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_REV = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_REV = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_SIG_STR_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_SIG_STR_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_SIG_STR_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_SIG_STR_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_TOTAL_STR_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_TOTAL_STR_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_TOTAL_STR_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_TOTAL_STR_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_TD_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_TD_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_TD_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_TD_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_HEAD_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_HEAD_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_HEAD_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_HEAD_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_BODY_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_BODY_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_BODY_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_BODY_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_LEG_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_LEG_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_LEG_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_LEG_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_DISTANCE_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_DISTANCE_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_DISTANCE_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_DISTANCE_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_CLINCH_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_CLINCH_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_CLINCH_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_CLINCH_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_GROUND_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_GROUND_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_GROUND_att = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_opp_GROUND_landed = table.Column<double>(type: "REAL", nullable: true),
                    R_avg_CTRL_timeseconds = table.Column<double>(name: "R_avg_CTRL_time(seconds)", type: "REAL", nullable: true),
                    R_avg_opp_CTRL_timeseconds = table.Column<double>(name: "R_avg_opp_CTRL_time(seconds)", type: "REAL", nullable: true),
                    R_total_time_foughtseconds = table.Column<double>(name: "R_total_time_fought(seconds)", type: "REAL", nullable: true),
                    R_total_rounds_fought = table.Column<int>(type: "INTEGER", nullable: true),
                    R_total_title_bouts = table.Column<int>(type: "INTEGER", nullable: true),
                    R_current_win_streak = table.Column<int>(type: "INTEGER", nullable: true),
                    R_current_lose_streak = table.Column<int>(type: "INTEGER", nullable: true),
                    R_longest_win_streak = table.Column<int>(type: "INTEGER", nullable: true),
                    R_wins = table.Column<int>(type: "INTEGER", nullable: true),
                    R_losses = table.Column<int>(type: "INTEGER", nullable: true),
                    R_draw = table.Column<int>(type: "INTEGER", nullable: true),
                    R_win_by_Decision_Majority = table.Column<double>(type: "REAL", nullable: true),
                    R_win_by_Decision_Split = table.Column<double>(type: "REAL", nullable: true),
                    R_win_by_Decision_Unanimous = table.Column<double>(type: "REAL", nullable: true),
                    R_win_by_KOTKO = table.Column<double>(name: "R_win_by_KO/TKO", type: "REAL", nullable: true),
                    R_win_by_Submission = table.Column<double>(type: "REAL", nullable: true),
                    R_win_by_TKO_Doctor_Stoppage = table.Column<double>(type: "REAL", nullable: true),
                    R_Stance = table.Column<string>(type: "TEXT", nullable: true),
                    R_Height_cms = table.Column<double>(type: "REAL", nullable: true),
                    R_Reach_cms = table.Column<double>(type: "REAL", nullable: true),
                    R_Weight_lbs = table.Column<double>(type: "REAL", nullable: true),
                    B_age = table.Column<double>(type: "REAL", nullable: true),
                    R_age = table.Column<double>(type: "REAL", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Fights", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Fights");
        }
    }
}
